language: java
install: true

os: linux
dist: xenial
jdk: openjdk8

script:
  - ./gradlew --no-daemon --stacktrace --console=plain check

after_success:
  - ./gradlew --no-daemon --stacktrace --console=plain jacocoTestReport coveralls

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
